export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR';

export const SEARCH_ORDERS = 'SEARCH_ORDERS';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD';

export const SET_TABLE_SORTING = 'SET_TABLE_SORTING';

export const TOGGLE_ORDER_CARD = 'TOGGLE_ORDER_CARD';
